name: Run Automation Tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  schedule:
    - cron: '0 0 * * *'   # 07:00 WIB (== 00:00 UTC)
    - cron: '0 10 * * *'  # 17:00 WIB (== 10:00 UTC)
    - cron: '5 13 * * *'   # 20:05 WIB

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber tests
        id: run-tests
        run: |
          npm run test || echo "TESTS_FAILED=true" >> $GITHUB_ENV

      - name: Generate HTML Report
        if: always()
        run: npm run report

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: reports/html/

      - name: Send summary email
        if: always()
        run: npm run email:report
        env:
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          NODEMAILER_USER: ${{ secrets.EMAIL_USER }}
          NODEMAILER_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

      - name: Fail the job if tests failed
        if: env.TESTS_FAILED == 'true'
        run: exit 1